proyecto_HolaMundo/about/urls.py
from django.urls import path, re_path
from .views import about

app_name = 'about'

urlpatterns = [
    path("acerca-de-mi-empresa", about, name="about")
]

proyecto_HolaMundo/home/urls.py
from pathlib import Path
from django.urls.conf import path
from .views import micasa

urlpatterns = [
    path('', micasa, name='home1')
]

proyecto_HolaMundo/proyecto_HolaMundo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('sintactico.urls')),
    path('',include('about.urls')),
]

proyecto_HolaMundo/sintactico/urls.py
from django.urls import path
from .views import principal

app_name = 'sintactico'

urlpatterns = [
    path("sintactico-estructural-patrones/", principal, name="patrones")
]

proyecto_HolaMundo/about/models.py
from django.db import models

# Create your models here.

proyecto_HolaMundo/grafo/models.py
from django.db import models

# Create your models here.

proyecto_HolaMundo/home/models.py
from django.db import models

# Create your models here.
class Paciente(models.Model):

    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = ("Paciente")
        verbose_name_plural = ("Pacientes")

    def __str__(self):
        return self.name

    #def get_absolute_url(self):
     #   return reverse("Paciente_detail", kwargs={"pk": self.pk})

class tessiu(models.Model):

    temperature = models.FloatField(verbose_name="temperatura")
    color = models.FloatField()
    inflamation = models.FloatField(verbose_name="inflamacion")
    name = models.ForeignKey(Paciente, on_delete=models.CASCADE,blank=True, null=True)
    
    

    class Meta:
        verbose_name = "tejido"
        verbose_name_plural = "tejidos"

    def __str__(self):
        return 'temperatura: '+ str(self.temperature) + ' color: ' + str(self.color) + ' inflamacion: ' + str(self.temperature) 

    def get_absolute_url(self):
        return reverse("tessiu_detail", kwargs={"pk": self.pk})

proyecto_HolaMundo/sintactico/models.py
from django.db import models

# Create your models here.

proyecto_HolaMundo/about/views.py
#from django.http.response import HttpResponse
from django.shortcuts import render

# Create your views here.

def about(request):

    resultado = mifuncion(request)
    template_name='about/about.html'
    return render(request, template_name, )

def mifuncion(args):
     return ''




"""  
    textHtml = 

    <h1> Hola mundo </h1>

    <ul>

    <li> Donde
    <li> la fiesta

    </ul>  

    return HttpResponse(textHtml)
"""
    

proyecto_HolaMundo/grafo/views.py
from django.shortcuts import render

# Create your views here.

proyecto_HolaMundo/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import tessiu
# Create your views here.

def micasa(request):
    Lista =tessiu.objects.get_queryset()

    ProcesaLista(Lista)
    template_name='home/home.html'
    return render(request, template_name, {'l':Lista})
    
def ProcesaLista(L):
    for i in L:
        if i.color > 20:
            print(i.pk, i.color, 'tejido enfermo')
        else: 
            print(i.pk , i.color, 'tejido no enfermo')    

        # return HttpResponse('<h1>Hola mundo</h1>')

proyecto_HolaMundo/sintactico/views.py
from django.http.response import HttpResponse
from django.shortcuts import render

# Create your views here.

def principal(request):
    template_name='sintactico/sintactico.html'
    diccionariocontexto = {'lista' :[1,2,3,4,5]}
    return render(request, template_name,diccionariocontexto)


#def principal(request):
#   return HttpResponse('<h1>Sintactico Estructural</h1>')

proyecto_HolaMundo/about/templates/about/about.html
{% extends 'home/home.html' %}

{% block contenido %}

<h1>Bienvenido a mi acerca de</h1>
<p>
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Pariatur culpa odio commodi, non voluptatibus facilis. Earum, ut unde corporis alias sit veniam cum dolorem, ullam rem praesentium eligendi aliquid maiores?
</p>

<h2>mi nombre de usuario es: {{nombreusuario}} </h2>
<h2>mi edad es: {{edad}}</h2>

{% endblock contenido %}

{% block footer %}
<p>

    about
</p>
  
{% endblock footer %}

proyecto_HolaMundo/home/templates/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pagina principal ISI</title>
    <body style="color: rgb(43, 43, 97); background-color: #EA899A; font-family: Georgia, Cambria, serif; font-size: 16px;"></body>

    <!--style>
        table{

            width: 50%;

        }
        td{

            border: 2px solid black;

        }


    </style-->
</head>
<body>
    <ul>
        <li><a href="{% url 'home1' %}">home</a></li>
        <li><a href="{% url 'sintactico:patrones' %}">sintactico</a></li>
        <li><a href="{% url 'about:about' %}">about</a></li>
    </ul>

   

    {% block contenido %}
     
    {% endblock contenido %}


    <ul>

        <table>

            <thead>

                <tr>
                    <td>pk </td>
                    <td>Temperatura </td>
                    <td>Color</td>
                    <td>Inflamacion</td>
                </tr>
            </thead>
            <tbody>

                 {% for elemento in l %}
                    <tr>
                        <td style="border: 2px solid rgb(233, 33, 33);">{{elemento.pk}}</td>
                        
                        {% if elemento.temperature > 50 %}
                        <td style="border: 2px solid  rgb(214, 36, 51);">{{elemento.temperature}}</td>
                        
                        {% else %}
                        <td style="border: 2px solid  rgb(7, 0, 0)ck;">{{elemento.temperature}}</td>
                        
                        {% endif %}
                            
                        
                        <td style="border: 2px solid rgb(19, 196, 57);">{{elemento.color}}</td>
                        <td style="border: 2px solid rgb(186, 216, 14);">{{elemento.inflamation}}</td>
                        
                    </tr>
      
                {% endfor %}
            </tbody>

        </table>
        

    </ul>
    
    <hr>
    {% block footer %}
      <p>Inicio</p>
    {% endblock footer %}
</body>
</html>

proyecto_HolaMundo/sintactico/templates/sintactico/sintactico.html
{% extends 'home/home.html' %}

{% block contenido %}
  <h1>
        Reconocimiento de Patronnes Sintactico Estructural: Deteccion de cancer de mama
    </h1>
{% endblock contenido %}
    
{% block footer %}
  <p>
    Sintactico
  </p>
{% endblock footer %}